packages:
  - 'packages/framework/block-std'
  - 'packages/framework/global'
  - 'packages/framework/inline'
  - 'packages/framework/store'
  - 'packages/framework/sync'
  - 'packages/blocks'
  - 'packages/docs'
  - 'packages/playground'
  - 'packages/presets'
  - 'packages/simple'
  - 'packages/vue-block-editor'
  - 'packages/vue-web-component'
  - 'packages/lit-component'
  - 'packages/web-component'
  - 'packages/vue-playground'
  - 'packages/simple-editor'
